spring:
  application:
    name: servicemedianos

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres
    username: postgres.jjnalqrrjvqfcmhefbge
    password: tfNw2Fs2gnJp3mYX

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  config:
    import: optional:configserver:

server:
  port: 9001

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: http://localhost:9003/eureka/
